# **Loading Torch Library**

In [1]:
import torch

# Reshaping, Stacking, Squeezing, and Unsqueezing Tensors in PyTorch

Often, you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them. This is a common requirement in deep learning workflows where tensor shapes must align with model expectations.

## Popular Tensor Manipulation Methods

| Method                                      | One-line Description                                                                                      |
|---------------------------------------------|----------------------------------------------------------------------------------------------------------|
| [torch.reshape(input, shape)](https://pytorch.org/docs/stable/generated/torch.reshape.html) | Reshapes `input` to `shape` (if compatible). Can also use `torch.Tensor.reshape()`.                        |
| [Tensor.view(shape)](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.view)          | Returns a **view** of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [torch.stack(tensors, dim=0)](https://pytorch.org/docs/stable/generated/torch.stack.html)    | Concatenates a sequence of `tensors` along a new dimension (`dim`). All tensors must be the same size.    |
| [torch.squeeze(input)](https://pytorch.org/docs/stable/generated/torch.squeeze.html)          | Removes all dimensions of size 1 from `input`.                                                           |
| [torch.unsqueeze(input, dim)](https://pytorch.org/docs/stable/generated/torch.unsqueeze.html) | Returns `input` with a dimension of size 1 added at position `dim`.                                       |
| [torch.permute(input, dims)](https://pytorch.org/docs/stable/generated/torch.permute.html)    | Returns a **view** of the original `input` with its dimensions permuted (rearranged) according to `dims`. |

---

## Why Use These Methods?

Deep learning models (neural networks) rely heavily on manipulating tensors. Due to the rules of matrix multiplication and tensor operations, shape mismatches often cause errors. These methods help ensure that the right elements of your tensors align and mix correctly with elements of other tensors.

For example:

- **Reshaping** allows you to flatten or reorganize data to fit layer inputs.
- **Viewing** provides a memory-efficient way to change tensor shape without copying data.
- **Stacking** helps combine multiple tensors into a batch or along a new dimension.
- **Squeezing/Unsqueezing** add or remove singleton dimensions to match expected input shapes.
- **Permuting** rearranges tensor dimensions, which is useful for changing data layout (e.g., from channels-first to channels-last).

---

## Practical Example: Creating and Manipulating a Tensor

Let's try these methods out by first creating a tensor and then applying some of these operations.

In [23]:
X = torch.arange(1, 8) # Create a tensor from numbers from 1 to 7
print(X) # print the tensor
print(X.shape) # print tensor's shape

tensor([1, 2, 3, 4, 5, 6, 7])
torch.Size([7])


> Now let's add an extra dimension with `torch.reshape()`

In [24]:
X_reshaped = X.reshape(1, 7) # reshaping tensor X by adding dimension
print(X_reshaped) # print the tensor
print(X_reshaped.shape) # print the tensor's shape

tensor([[1, 2, 3, 4, 5, 6, 7]])
torch.Size([1, 7])


> Now let's add an extra dimension with `torch.view()`

In [25]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723

Z = X.view(1, 7) # creating tensor z with copy of x then reshaping tensor z by adding dimension
print(Z) # print the tensor
print(Z.shape) # print the tensor's shape

tensor([[1, 2, 3, 4, 5, 6, 7]])
torch.Size([1, 7])


**BUT** Changing **values** of `Z` will changes **values** of `X` as well **BUT dimesions will remain**..

Lets Try?

In [26]:
print(f"Tensor `X` before changing tensor `Z`: {X}") # print tensor `X` before changing `Z` tensor values..

Z [:,0] = 5 # changing the first value of tensor `Z` to 5 instead of 1

print(f"Tensor `Z`: {Z}") # print `Z` tensor after changing the first value
print(f"Tensor `X` after changing tensor `Z`: {X}") # print `X` tensor and observe the first value, it changed to 5 also! :)

# Don't Forget that only values change in view() NOT dimensions

Tensor `X` before changing tensor `Z`: tensor([1, 2, 3, 4, 5, 6, 7])
Tensor `Z`: tensor([[5, 2, 3, 4, 5, 6, 7]])
Tensor `X` after changing tensor `Z`: tensor([5, 2, 3, 4, 5, 6, 7])


If we wanted to stack our new tensor on top of itself five times, we could do so with `torch.stack()` .

In [34]:
X_stacked_rows = torch.stack([X, X, X], dim=0) # creating new tensor `X_stacked` containing `X` in rows >> NOTE: dim=0 stack in rows while dim=1 stack in columns
X_stacked_columns = torch.stack([X, X, X], dim=1) # creating new tensor `X_stacked` containing `X` in columns

print(X_stacked_rows)
print(X_stacked_rows.shape)

print('-'*50) # seperator

print(X_stacked_columns)
print(X_stacked_columns.shape)

tensor([[5, 2, 3, 4, 5, 6, 7],
        [5, 2, 3, 4, 5, 6, 7],
        [5, 2, 3, 4, 5, 6, 7]])
torch.Size([3, 7])
--------------------------------------------------
tensor([[5, 5, 5],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7]])
torch.Size([7, 3])


How about removing all single dimensions from a tensor?

To do so you can use `torch.squeeze()`

In [35]:
print(f"Previous tensor: {X_reshaped}")
print(f"Previous shape: {X_reshaped.shape}")

# Remove extra dimension from x_reshaped
X_squeezed = X_reshaped.squeeze()
print(f"\nNew tensor: {X_squeezed}")
print(f"New shape: {X_squeezed.shape}")

Previous tensor: tensor([[5, 2, 3, 4, 5, 6, 7]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5, 2, 3, 4, 5, 6, 7])
New shape: torch.Size([7])



> **NOTE:**  this as squeezing the tensor to only have dimensions over 1.

In [44]:
print(f"Previous tensor: {X}")
print(f"Previous shape: {X.shape}")

print('-'*50) # seperator

X_wrong_squeezed = X.squeeze() # Remove extra dimension from `X` (`X` has only 1 dimension)
print(f"New tensor: {X_wrong_squeezed}")
print(f"New shape: {X_wrong_squeezed.shape}")

print('\nObservation? NOTHING CHANGED..Why? as we said before "squeezing the tensor to only have dimensions over 1.')

Previous tensor: tensor([5, 2, 3, 4, 5, 6, 7])
Previous shape: torch.Size([7])
--------------------------------------------------
New tensor: tensor([5, 2, 3, 4, 5, 6, 7])
New shape: torch.Size([7])

Observation? NOTHING CHANGED..Why? as we said before "squeezing the tensor to only have dimensions over 1.


And to do the reverse of `torch.squeeze()` you can use `torch.unsqueeze()` to add a dimension value of 1 at a specific inden

In [47]:
print(f"Previous tensor: {X_squeezed}")
print(f"Previous shape: {X_squeezed.shape}")

# Add extra dimension to X_squeezed
X_unsqueezed = X_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {X_unsqueezed}")
print(f"New shape: {X_unsqueezed.shape}")

Previous tensor: tensor([5, 2, 3, 4, 5, 6, 7])
Previous shape: torch.Size([7])

New tensor: tensor([[5, 2, 3, 4, 5, 6, 7]])
New shape: torch.Size([1, 7])


You can also rearrange the order of axes values with `torch.permute(input, dims)`.
Where the input gets turned into a `view` with new `dims` .

In [48]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1)  # shifts axis ( 0 -> 1, 1 -> 2, 2 -> 0 ) .... in other words (2, 0, 1) are indexs of `x_original` tensor

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


# **Thanks! Don't forget to Star the repo 🫡⭐**