# **Loading Torch Library**

In [1]:
import torch

# 1. Manipulating Tensors (Tensor Operations)

In deep learning, data such as images, text, video, audio, and even protein structures are represented as **tensors**.

A model learns by analyzing these tensors and performing a series of operations—sometimes numbering in the millions or more—to extract and represent patterns in the input data.

These tensor operations often include:

- **Addition**
- **Subtraction**
- **Element-wise Multiplication**
- **Division**
- **Matrix Multiplication**

Together, these operations form the foundation of computations in deep learning models, enabling them to process and learn from complex, high-dimensional data.

---

> **Note:**  
> A **tensor** is a generalization of scalars (0D), vectors (1D), and matrices (2D) to potentially higher dimensions (3D, 4D, etc.), making them a flexible and powerful data structure for machine learning and deep learning tasks.

### Basic Operations

Let's start with a few of the fundamental operations: **addition (+)**, **subtraction (−)**, and **multiplication (×)**.
These operations work just as you would expect—they are applied element-wise when working with tensors of the same shape.

In [13]:
# create a tensor of values and subtract 2 from it
tensor = torch.tensor([4, 6, 7])

print(tensor - 2) # subtract 2 from tensor

# OR

print(tensor.sub(2))

tensor([2, 4, 5])
tensor([2, 4, 5])


In [12]:
# create a tensor of values and add 2.5 to it
tensor2 = torch.tensor([4, 6, 7])

print(tensor2 + 2.5) # add 2.5 to tensor

# OR

print(tensor2.add(2.5))

tensor([6.5000, 8.5000, 9.5000])
tensor([6.5000, 8.5000, 9.5000])


In [11]:
# create a tensor of values and multiply it by scalar 10
tensor3 = torch.tensor([4, 6, 7])

print(tensor3 * 10) # multiply tensor by 10

# OR

print(tensor3.multiply(10)) # you can short multiply with `.mul(10)`

tensor([40, 60, 70])
tensor([40, 60, 70])


> **Note:**  
> Tensors do **NOT** change **unless reassigned**

In [9]:
print(tensor) # output [4, 6, 7] NOT [2, 4, 5]
print(tensor2) # output [4, 6, 7] NOT [6.5000, 8.5000, 9.5000]
print(tensor3) # output [4, 6, 7] NOT [40, 60, 70]

tensor([4, 6, 7])
tensor([4, 6, 7])
tensor([4, 6, 7])


In [10]:
# Let's try reassigning

tensor = tensor - 2
tensor2 = tensor2 + 2.5
tensor3 = tensor3 * 10

print(tensor) # output [2, 4, 5]
print(tensor2) # output [6.5000, 8.5000, 9.5000]
print(tensor3) # output [40, 60, 70]

tensor([2, 4, 5])
tensor([6.5000, 8.5000, 9.5000])
tensor([40, 60, 70])


## Matrix multiplication (is all you need)

One of the most common operations in machine learning and deep learning algorithms (like neural networks) is [matrix multiplication](https://en.wikipedia.org/wiki/Matrix_multiplication).

PyTorch implements matrix multiplication functionality in the [torch.matmul()](https://pytorch.org/docs/stable/generated/torch.matmul.html) method.

The main two rules for matrix multiplication to remember are:

1. **The inner dimensions must match:**
    - `(3, 2) @ (3, 2)` won't work
    - `(2, 3) @ (3, 2)` will work
    - `(3, 2) @ (2, 3)` will work

2. **The resulting matrix has the shape of the outer dimensions:**
    - `(2, 3) @ (3, 2)` → `(2, 2)`
    - `(3, 2) @ (2, 3)` → `(3, 3)`

> **Note:**  
> "@" in Python is the symbol for matrix multiplication.

---

**The difference** between **element-wise multiplication** and **matrix multiplication** is the addition of values.

- e.g. `tensor` variable with values `[1, 2, 3]`:

| Operation                  | Calculation                | Code                        |
|----------------------------|----------------------------|-----------------------------|
| **Element-wise multiplication**| [1\*1, 2\*2, 3\*3] = [1, 4, 9] | `tensor * tensor`           |
| **Matrix multiplication**      | [1\*1 + 2\*2 + 3\*3] = [14]   |`tensor.matmul(tensor)`

**Let's create a tensor and perform element-wise multiplication and matrix multiplication on it.**

In [16]:
Tensor = torch.tensor([[1,2,3],
                       [4,5,6]])

print(Tensor.shape) # Getting `Tensor` shape

torch.Size([2, 3])


> **Element-wise multiplication**

In [19]:
print(Tensor * Tensor)

tensor([[ 1,  4,  9],
        [16, 25, 36]])


> **Matrix Multiplication**

In [20]:
print(Tensor.matmul(Tensor)) # WRONG due to shapes! (2 x 3) * (2 x 3)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [21]:
print(Tensor.matmul(Tensor.T)) # WORKED as we used Transposed matrix for Tensor and now become (2 x 3) * (3 x 2)

tensor([[14, 32],
        [32, 77]])


> You can do **matrix multiplication by hand** but it's **NOT recommended.**
The in-built `torch.matmul()` method is **faster**.

In [31]:
%%time

# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)

tensor = torch.tensor([4, 6, 7])

value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

print(value)

tensor(101)
CPU times: user 1.65 ms, sys: 57 µs, total: 1.71 ms
Wall time: 1.38 ms


In [32]:
%%time

print(tensor.matmul(tensor.T))

tensor(101)
CPU times: user 1.32 ms, sys: 0 ns, total: 1.32 ms
Wall time: 1.18 ms


# 2. Dealing with Tensor Shapes

One of the most common errors in deep learning is related to **tensor shapes** (often called "shape errors").

Because much of deep learning involves multiplying and performing operations on matrices, and matrices have strict rules about what shapes and sizes can be combined, **shape mismatches** are a frequent source of bugs.

> **Tip:**  
> Always check the shapes of your tensors before performing operations. Shape mismatches can lead to confusing errors and are one of the most common issues you'll encounter in deep learning workflows.

In [33]:
# Shapes need to be in the right way
tensor_A = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
], dtype=torch.float32)

tensor_B = torch.tensor([
    [7, 10],
    [8, 11],
    [9, 12]
], dtype=torch.float32)

# This will raise an error due to incompatible shapes for matrix multiplication
torch.matmul(tensor_A, tensor_B)  # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

We can make matrix multiplication work between `tensor_A` and `tensor_B` by making their **inner dimensions** match.

One of the ways to do this is with a **transpose** (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:

- `torch.transpose(input, dim0, dim1)` – where `input` is the desired tensor to transpose and `dim0` and `dim1` are the dimensions to be swapped.
- `tensor.T` – where `tensor` is the desired tensor to transpose.

Let's try the latter.

In [40]:
print("Before Transposing... \n")
print(tensor_A)
print('-'*40)
print("After Transposing... \n")
print(tensor_A.T)

Before Transposing... 

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
----------------------------------------
After Transposing... 

tensor([[1., 3., 5.],
        [2., 4., 6.]])


> **The operation** works when `tensor_B` is **transposed**

In [41]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


> You can also use `torch.mm()` which is a short for `torch.matmul()`

In [43]:
# the last code but with `torch.mm()` instead
mm_output = torch.mm(tensor_A, tensor_B.T)
print(mm_output)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])


# 3. Neural networks are full of matrix multiplications and dot products.

The [torch.nn.Linear()](https://pytorch.org/docs/stable/generated/torch.nn.Linear.html) module (also known as a feed-forward layer or fully connected layer) implements a matrix multiplication between an input `x` and a weights matrix `A`:

$$
y = x \cdot A^T + b
$$

**Where:**

- `x` is the input to the layer (in deep learning, this is often a stack of layers like `torch.nn.Linear()` and others on top of each other).
- `A` is the weights matrix created by the layer. This starts out as random numbers that get adjusted as a neural network learns to better represent patterns in the data (notice the "T" for transpose, because the weights matrix gets transposed).
  - **Note:** You might also often see `W` or another letter like `X` used to represent the weights matrix.
- `b` is the bias term used to slightly offset the weights and inputs.
- `y` is the output (a manipulation of the input in the hopes to discover patterns in it).

This is a linear function (you may have seen something like $$ y = mx + b $$ in high school or elsewhere), and can be used to draw a straight line!

---

Let's play around with a linear layer.

Try changing the values of `in_features` and `out_features` below and see what happens.

In [53]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(52)

# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2,  # in_features = matches inner dimension of input
                        out_features=8) # out_features = describes outer value

x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[ 1.8014, -0.1416,  1.0696,  1.1630,  0.4917, -0.1042,  2.2159,  0.2706],
        [ 3.2157,  0.2179,  2.9151,  1.8537, -0.1434, -0.3089,  4.4574,  0.9455],
        [ 4.6300,  0.5773,  4.7606,  2.5445, -0.7785, -0.5136,  6.6989,  1.6205]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 8])


# **Thanks! Don't forget to Star the repo 🫡⭐**