# **Loading Torch Library**

In [2]:
import torch

### 1. Indexing (selecting data from tensors)

Sometimes you'll want to select specific data from tensors (for example, only the first column or second row).

To do so, you can use indexing.

If you've ever done indexing on Python lists or NumPy arrays, indexing in PyTorch with tensors is very similar.

In [21]:
# Create tensor `X`
X = torch.arange(1, 10).reshape(1, 3, 3)

print(X) # print tensor `X`
print(X.shape) # print tensor `X` shape

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
torch.Size([1, 3, 3])


Indexing values goes outer dimension -> inner dimension (check out the square brackets).

In [26]:
# Indexing by brackets
print(f"First square bracket:\n{X[0]}")
print(f"Second square bracket: {X[0][0]}")
print(f"Third square bracket: {X[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


You can also use `:` to specify "all values in this dimension" and then use a comma (`,`) to add another dimension.

In [24]:
# Get all values of 0th dimension and the 0 index of 1st dimension
print(X[:,0])

tensor([[1, 2, 3]])


In [25]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
print(X[:,:,1])

tensor([[2, 5, 8]])


In [27]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
print(X[:, 1, 1])

tensor([5])


In [29]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
print(X[0, 0, :])  # same as X[0][0]

tensor([1, 2, 3])


### 2. PyTorch tensors & NumPy

Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

- [torch.from_numpy(ndarray)](https://pytorch.org/docs/stable/generated/torch.from_numpy.html) - NumPy array -> PyTorch tensor.
- [torch.Tensor.numpy()](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) - PyTorch tensor -> NumPy array.

Let's try them out.

In [42]:
import numpy as np

# Create np array
array = np.arange(1, 8)

# # NumPy array to tensor
tensor = torch.from_numpy(array)

print(tensor, type(tensor)) # print `tensor` and it's dtype
print(array, type(array)) # print `array` and it's dtype

tensor([1, 2, 3, 4, 5, 6, 7]) <class 'torch.Tensor'>
[1 2 3 4 5 6 7] <class 'numpy.ndarray'>


> Creating a new array with modifying the old one doesn't Change or affect tensors that are connected to this array and vice versa..

Example:

In [44]:
arr = np.array([1, 2, 3])
tensor_1 = torch.from_numpy(arr) # Connect `tensor_1` and `arr` to shared memory.

# Creating a new array with modifying the old one
arr = arr + 100

print(tensor_1) # `tensor_1` stays the same, `arr` doesn't affect `tensor_1`
print(arr) # output [101, 102, 103]

tensor([1, 2, 3])
[101 102 103]


BUT and there is a **BUT**

> Modifying the array it self (e.g. by indexing) **DOES** **Change** and **affect** tensors that are connected to this array as they have the **SAME MEMORY** vice versa..

Example:

In [45]:
arr_2 = np.array([1, 2, 3])
tensor_2 = torch.from_numpy(arr_2) # Connect `tensor_2` and `arr_2` to shared memory.

# Modifying the array with index
arr_2[0] = 100

print(tensor_2) # `tensor_2` affected, `arr_2` does affect `tensor_2` due to sharing memory
print(arr_2) # output [100, 2, 3]

tensor([100,   2,   3])
[100   2   3]


### 3. Reproduciability

In [46]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.2996, 0.9271, 0.0570, 0.8050],
        [0.0994, 0.2809, 0.8646, 0.8949],
        [0.9786, 0.7801, 0.8927, 0.2644]])

Tensor B:
tensor([[0.7135, 0.9586, 0.7264, 0.9291],
        [0.2026, 0.2789, 0.0487, 0.1970],
        [0.7921, 0.5812, 0.0259, 0.8703]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [48]:
# Set the random seed
RANDOM_SEED = 42  # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.manual_seed(seed=RANDOM_SEED)  # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# **Thanks! Don't forget to Star the repo 🫡⭐**