# **Loading Torch Library**

In [1]:
import torch

## **1. Random Tensors**
When building machine learning models with PyTorch, it's rare that you'll create tensors manually (like we've been doing so far). Instead, a **machine learning model typically starts with large random tensors of numbers**. These random numbers are then adjusted as the model processes data to better represent patterns within it.

In essence:
Start with random numbers → look at data → update random numbers → look at data → update random numbers... and so on.

As a data scientist, you define how the machine learning model starts (initialization), interprets the data (representation), and updates its random numbers (optimization).

Now, let's see how to create a tensor of random numbers.
We can do this using [torch.rand()](https://pytorch.org/docs/stable/generated/torch.rand.html) and passing in the desired size as a parameter.

In [12]:
# Create random tensors of size (dimensions) 3, 4
random_tensors = torch.rand(size =(3, 4)) # or ```torch.rand(3, 4)```

print(random_tensors) # Print random values in `random_tensors`
print(random_tensors.dtype) # Print dtypes of values in `random_tensors`
print(random_tensors.shape) # Get the shape of `random_tensors`
print(random_tensors.ndim) # Get the number of dimensions of `random_tensors`

tensor([[0.5827, 0.1094, 0.3765, 0.6203],
        [0.1388, 0.3229, 0.9218, 0.1989],
        [0.8863, 0.3723, 0.0837, 0.2229]])
torch.float32
torch.Size([3, 4])
2


In [13]:
# Create random tensors of size (dimensions) 224,224,3
random_tensors2 = torch.rand(size =(224,224,3))

print(random_tensors2) # Print random values in `random_tensors2`
print(random_tensors2.dtype) # Print dtypes of values in `random_tensors2`
print(random_tensors2.shape) # Get the shape of `random_tensors2`
print(random_tensors2.ndim) # Get the number of dimensions of `random_tensors2`

tensor([[[0.2512, 0.5522, 0.6157],
         [0.0318, 0.6483, 0.1315],
         [0.6464, 0.0501, 0.0621],
         ...,
         [0.2016, 0.2795, 0.9794],
         [0.8632, 0.8824, 0.3569],
         [0.8779, 0.4705, 0.5695]],

        [[0.5371, 0.7936, 0.7272],
         [0.2523, 0.9907, 0.9835],
         [0.0572, 0.4154, 0.6843],
         ...,
         [0.3699, 0.9390, 0.4791],
         [0.3363, 0.6960, 0.5175],
         [0.2429, 0.8246, 0.4905]],

        [[0.1613, 0.9428, 0.7809],
         [0.9035, 0.9337, 0.1273],
         [0.1568, 0.1473, 0.1371],
         ...,
         [0.1412, 0.9363, 0.6326],
         [0.3473, 0.2935, 0.6847],
         [0.1102, 0.6248, 0.4411]],

        ...,

        [[0.3007, 0.5159, 0.9325],
         [0.8161, 0.7842, 0.3946],
         [0.7562, 0.8359, 0.2315],
         ...,
         [0.1954, 0.9125, 0.3693],
         [0.4987, 0.3555, 0.8710],
         [0.6997, 0.7264, 0.4646]],

        [[0.9600, 0.0025, 0.8785],
         [0.0965, 0.8067, 0.3467],
         [0.

## **2. Zeros & Ones**

In [14]:
# Create tensor of all zeros of size (dimensions) 3, 4
zeros_tensors = torch.zeros(size =(3, 4))

print(zeros_tensors)
print(zeros_tensors.dtype)
print(zeros_tensors.shape)
print(zeros_tensors.ndim)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32
torch.Size([3, 4])
2


In [16]:
# Create tensor of all ones of size (dimensions) 3, 4
ones_tensors = torch.ones(size =(3, 4))

print(ones_tensors)
print(ones_tensors.dtype)
print(ones_tensors.shape)
print(ones_tensors.ndim)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32
torch.Size([3, 4])
2


# **Thanks! Don't forget to Star the repo 🫡⭐**

