# **Loading Torch Library**

In [1]:
import torch

# Creating a Range and Tensors in PyTorch

Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100. You can use `torch.arange(start, end, step)` to create such a range. Here's how it works:

- **`start`**: The beginning of the range (e.g., 0).
- **`end`**: The end of the range (e.g., 10). Note that the end value is exclusive.
- **`step`**: The increment between each value in the range (e.g., 1).

**Note**: In Python, you can use the built-in `range()` function to create a range of numbers. However, in PyTorch, `torch.range()` is deprecated and may result in an error in the future. Therefore, it's recommended to use `torch.arange()` for creating ranges in PyTorch.

In [8]:
# Use torch.arange() since, torch.range() is deprecated

# Creating a range of numbers from 0 to 10
arange_numbers = torch.arange(0, 10)
print(arange_numbers)

# Creating a range of numbers from 0 to 20 and step of 2.2
arange_numbers2 = torch.arange(0, 20, 2.2)
print(arange_numbers2)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 0.0000,  2.2000,  4.4000,  6.6000,  8.8000, 11.0000, 13.2000, 15.4000,
        17.6000, 19.8000])


# Tensor Datatypes in PyTorch

There are [many different tensor datatypes available](https://pytorch.org/docs/stable/tensors.html#data-types) in PyTorch. Some are specific for CPU and some are better for GPU. Getting to know which is which can take some time.

Generally, if you see `torch.cuda` anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is `torch.float32` or `torch.float`. This is referred to as "32-bit floating point". But there's also:

- **16-bit floating point**: `torch.float16` or `torch.half`
- **64-bit floating point**: `torch.float64` or `torch.double`

Additionally, there are 8-bit, 16-bit, 32-bit, and 64-bit integers, plus more!

**Note that**:
- An integer is a flat round number like 7, whereas a float has a decimal, such as 7.0.
- Default datatype for tensors is float32

**Let's see how to create some tensors with specific datatypes. We can do so using the dtype parameter.**

In [11]:
Tensor = torch.tensor([3,4,5],
                      dtype= None, # Using None will use default dtype of the values in Tensor (e.g. int64)
                      device= None, # Using None will use default device
                      requires_grad=False) # Register any operations on this Tensor
print(Tensor)
print(Tensor.shape)
print(Tensor.dtype)
print(Tensor.device)

tensor([3, 4, 5])
torch.Size([3])
torch.int64
cpu


Another Example..

In [14]:
Tensor2 = torch.tensor([3,4,5],
                      dtype= torch.float16, # Using float16 dtype (don't forget to `torch.` before dtype)
                      device= None, # Using None will use default device
                      requires_grad=False) # Register any operations on this Tensor
print(Tensor2)
print(Tensor2.shape)
print(Tensor2.dtype)
print(Tensor2.device)

tensor([3., 4., 5.], dtype=torch.float16)
torch.Size([3])
torch.float16
cpu


# **Thanks! Don't forget to Star the repo 🫡⭐**